image: "ubuntu:latest"

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get update
    - apt-get install -y python3-pip git wget
    - pip3 install --user -r ./requirements.txt

build:
    stage: deploy
    script:
        - LC_ALL=C.UTF-8 LANG=C.UTF-8 PATH="$HOME/.local/bin:$PATH" ./test.sh
    artifacts:
        paths:
            - site
        expire_in: 1 week
